spring:
  application:
    name: sekretess-business-app
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./sekretess-business-app-db}
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  rabbitmq:
    addresses: amqps://pveuzxms:EOv0mSE295ZAir9LmIK8fLEqKKmX7-V6@kangaroo.rmq.cloudamqp.com/pveuzxms



app:
  config:
    username: ${BUSINESS_USER_NAME:postnord}
    server:
      business:
        url: ${SEKRETESS_BUSINESS_SERVER_URL:https://business.sekretess.co}
      consumer:
        url: ${SEKRETESS_CONSUMER_SERVER_URL:https://consumer.sekretess.co}

